### ISSUE TITLE
opam install core results in ERROR while installing res.4.0.3

### ISSUE THREAD

**Issue by dvberkel** [mmottl/res#2]
I have a [Travis CI build](https://travis-ci.org/exercism/xocaml/builds/164637238) that fails with the message:

``` plain
==== ERROR [while installing res.4.0.3] ====

Internal error:

  https://bitbucket.org/mmottl/res/downloads/res-4.0.3.tar.gz is not available.
```

Going to [https://bitbucket.org/mmottl/res/](https://bitbucket.org/mmottl/res/) I am greeted with a message that the repository is deleted and moved over to GitHub.

What is a graceful way to resolve this problem?

**Comment by mmottl** [comment]
That's a bizarre error.  I have checked my sources and the OPAM repository and can't find any reference whatsoever to the old bitbucket repository.  It has all been moved to GitHub years ago.  Are you sure you are fully up-to-date with regards to OPAM and the repository you are using?

**Comment by dvberkel** [comment]
Thanks for checking. It could well be a version problem. I took instructions from [this source](https://gist.github.com/avsm/6757425) almost verbatim. It was created three years ago, so it probably is out of date.

I will try to get newer version of opam working with the build.

**Comment by dvberkel** [comment]
For the record, after using the latest version of both OCaml and OPAM the problem went away.

Thanks again for your help
